spring:
  application:
    name: vivid-finance-api
  datasource:
    url: jdbc:postgresql://localhost:5432/vivid_db
    username: vivid_user
    password: test
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    default-schema: vivid_data

jwt:
  secret:
  accessTokenExpiration: 60000
  refreshTokenExpiration: 360000
